name: CI/CD Pipeline

on:
  pull_request:
    types: [opened, synchronize, reopened] # Executa em PRs abertos, atualizados ou reabertos
    branches: [develop] # Apenas para o branch develop
  push:
    branches: [develop, main, beta] # Executa em pushes diretos nas branches develop, main e beta

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  lint-and-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Garante que todos os commits sejam buscados
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run Commitlint
        if: github.event_name == 'pull_request'
        run: |
          npx commitlint --from=${{ github.event.pull_request.base.sha }} --to=${{ github.event.pull_request.head.sha }}

      - name: Run ESLint
        run: npx eslint .

  release:
    needs: lint-and-validate # Garante que o linting passe antes de prosseguir com a release
    if: |
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'develop') ||
      (github.event_name == 'push' && github.ref == 'refs/heads/develop')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Generate Timestamp Version
        id: timestamp_version
        run: |
          TIMESTAMP=$(date -u +"%Y%m%d%H%M%S") # Gera um timestamp no formato YYYYMMDDHHMMSS
          echo "TIMESTAMP_VERSION=$TIMESTAMP" >> $GITHUB_ENV

      - name: Prepare Semantic Release
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git commit --allow-empty -m "chore: generate next build with timestamp ${{ env.TIMESTAMP_VERSION }}" || true

      - name: Run Semantic Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
